### ISSUE TITLE
Prüfung fehlt, ob Domain verfügbar ist

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/yrewrite_metainfo#18]
Wenn ich in einer MultiDomain-Seite eine Domain dabei habe (die Hauptdomain), die **nicht** in YRewrite hinterlegt ist, dann hagelt es Fehler:
```
Error Call to a member function getName() on null
…/redaxo/src/addons/yrewrite_metainfo/fragments/yrewrite_metainfo/head.php 21
```
Hier sollte man ggf. vorher prüfen, ob $domain auch einen Wert hat.

**Comment by alxndr-w** [comment]
@iceman-fx Ich bin ja dankbar um die Meldungen, und freue mich, wenn Addons aktiv genutzt werden.

Bei so leichten Aufgaben - du bist ja selbst Autor eines Addons, wenn ich mich recht erinnere - wäre es super nett und ein bisschen angemessen, auch was zurück zu geben und nicht nur Fehler zu melden.

Durch die (oft unbezahlte) Wartung meiner Addons, auch genannt "Hobby", müssen weniger gepflegte Addons wie dieses eben bei mir zeitlich kürzertreten. Das nur zur Einschätzung, warum ich das jetzt in nächster Zeit nicht fixen werde. Ich bitte um Verständnis.
