### ISSUE TITLE
Prüfungen fehlen bei Ausgabe der Metadaten

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/yrewrite_metainfo#19]
z.B. wird 
`<link rel="manifest" href="[/media/](https://domain.de/media/)">`
ausgegeben, obwohl im entsprechenden Feld nichts hinterlegt wurde.

Ich vermute mal, dass dies auch die anderen Felder betrifft.

**Comment by alxndr-w** [comment]
Hi, ich nutze dieses Addon selbst und fülle alle Felder aus. Wenn du dich an dem Addon beteiligen möchtest, finanziell oder mit Arbeitszeit, dann gerne. Es ist ja eine lösbare Aufgabe.

**Comment by alxndr-w** [comment]
https://github.com/FriendsOfREDAXO/yrewrite_metainfo/blob/2.0.0-beta1/fragments/yrewrite_metainfo/head.php
