### ISSUE TITLE
Frage zur 2.0.0-beta1

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/yrewrite_metainfo#25]
Diese Funktion soll wegfallen: "Verwaltung von CSS-Variablen nicht mehr Teil des Addons - ersatzlos gestrichen"

Das ist sehr schade, da es eine tolle Funktion ist und dies bisher kein anderes vergleichbares Addon bietet.
Was ist denn der Grund dafür?

Wie kann man denn dann diese Funktion anderweitig wiederherstellen?

**Comment by alxndr-w** [comment]
Ich dachte, ich werde es nutzen. Tue ich aber nicht. Und mir war bis eben nicht bekannt, dass es irgendjemand nutzt.

Du kannst das Feld wie in 1.x definiert selbst wieder hinzufügen, ebenso die YForm-Tabelle. Oder als eigenes Addon rausbringen.
