### ISSUE TITLE
Weitere YRewrite-Issues lösen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/yrewrite_metainfo#5]
- [x] https://github.com/yakamara/redaxo_yrewrite/issues/145
- [x] https://github.com/yakamara/redaxo_yrewrite/issues/404
- [x] https://github.com/yakamara/redaxo_yrewrite/issues/391
- [x] https://github.com/yakamara/redaxo_yrewrite/issues/389
- [x] https://github.com/yakamara/redaxo_yrewrite/issues/390
- [x] https://github.com/yakamara/redaxo_yrewrite/issues/457
- [ ] https://github.com/yakamara/redaxo_yrewrite/issues/465
- [x] https://github.com/yakamara/redaxo_yrewrite/issues/168

**Comment by alxndr-w** [comment]
Die restlichen Issues sehe ich inzwischen nicht mehr in diesem Addon als notwendig, nur weil "YRewrite" vorne dran steht.
